source 'https://github.com/CocoaPods/Specs.git'

target 'SPXCacheManager', :exclusive => true do
  pod "SPXCacheManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SPXCacheManager", :path => "../"

  pod 'Kiwi'
end
